### PR TITLE
Optional JET runtime files

### PR DESCRIPTION
**Pull request by tfleis**

### CODE REVIEW

**Comment by pjBooms** [comment]
Thanx for another Pull Request. BTW, your previous Pull Request is already released and avalable from Maven Central under 0.2.1 version.

A few comments on this PR:

>>File optRtFile = new File( basedir, "target/jet/app/rt/bin/jfxwebkit.dll");
It works only on Windows. Could you please correct it to support Linux/OSX as well?
Please note that the native method libraries are in  lib/i368 with lib<LibName>.so mangling on Linux x86, on Linux amd64 they are in lib/amd64, and on OSX they are in lib with lib<LibName>.dylib mangling.

>>Add optional JET Runtime components to the package (e.g. javafx-webkit).
Please enumerate all of them like:

Add optional JET Runtime components to the package.
Available optional components:
      runtime_utilities, fonts, awt_natives, api_classes, jce,
      accessibility, javafx, javafx-webkit, nashorn, cldr

**Comment by pjBooms** [comment]
I think, it is even better to include another optional component such as nashorn and check it in platform independent maner: 

File optRtFile = new File( basedir, "target/jet/app/rt/lib/ext/nashorn.jar")

**Comment by tfleis** [comment]
I made the changes you told me. Sorry but I do not have the possibility to test it under Linux / Mac. I am no groovy expert. Maybe there is a better way than calling "assert false".

This was the last feature we need for the compilation of our tools. It would be nice if there were a possibility to configure the embedding of "tools.jar". Only a few of our applications need this file. Do you have an idea?

**Comment by pjBooms** [comment]
Thanx, I will merge and release the opt_rt_files feature on Monday.

BTW, we have just released the 0.3.0 version of the plugin with Test Run support. 
If you perform the Test Run (with 32-bit JET) javafx-webkit should be automatically added to the package without need to specify it explicitely.

Regarding tools.jar, please create an issue (https://github.com/excelsior-oss/excelsior-jet-maven-plugin/issues)  describing your use case in details, to let us discuss it there.

**Pull request merged**
